### ISSUE TITLE
ERROR: Your storage adapter does not inherit from the Storage Base.

### ISSUE THREAD

**Issue by pascalandy** [kelyvin/ghost-s3-service#1] opened 2016-10-05 04:15 UTC
Hi,

Have you encountered this error ? I don't understand where the error is coming from.
### Issue Summary

I know 0.10 brought a braking change for the s3 storage https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module

I now use this plug-in https://github.com/kelyvin/ghost-s3-service
### Steps to Reproduce
1. When starting Ghost 

```
> docker logs --follow $ctnID
npm info it worked if it ends with ok
npm info using npm@2.15.9
npm info using node@v4.6.0
npm info prestart ghost@0.11.1
npm info start ghost@0.11.1

> ghost@0.11.1 start /usr/src/ghost
> node index


ERROR: Your storage adapter does not inherit from the Storage Base.

 Error
    at Error.IncorrectUsage (/usr/src/ghost/core/server/errors/incorrect-usage.js:3:18)
    at Object.getStorage (/usr/src/ghost/core/server/storage/index.js:54:15)
    at setupMiddleware (/usr/src/ghost/core/server/middleware/index.js:126:44)
    at /usr/src/ghost/core/server/index.js:188:9
    at tryCatcher (/usr/src/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/usr/src/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/src/ghost/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/src/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/src/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

npm info poststart ghost@0.11.1
npm info ok
root@01:~/deploy-setup#
```
### Technical details:
- Ghost Version: 0.11.1
- Node Version: 4.6
- Browser/OS:  Ubuntu 16
- Database: mysql

Here is the logs when I install the module

```
npm info it worked if it ends with ok
npm info using npm@2.15.9
npm info using node@v4.6.0
npm info addNameTag [ 'ghost-s3-service', 'latest' ]
npm info attempt registry request try #1 at 4:08:26 AM
npm http request GET https://registry.npmjs.org/ghost-s3-service
npm http 200 https://registry.npmjs.org/ghost-s3-service
npm info retry fetch attempt 1 at 4:08:26 AM
npm info attempt registry request try #1 at 4:08:26 AM
npm http fetch GET https://registry.npmjs.org/ghost-s3-service/-/ghost-s3-service-1.0.2.tgz
npm http fetch 200 https://registry.npmjs.org/ghost-s3-service/-/ghost-s3-service-1.0.2.tgz
npm info install ghost-s3-service@1.0.2 into /usr/src/ghost/content/storage/ghost-s3
npm info installOne ghost-s3-service@1.0.2
npm info preinstall ghost-s3-service@1.0.2
npm info attempt registry request try #1 at 4:08:27 AM
npm http request GET https://registry.npmjs.org/aws-sdk
npm info attempt registry request try #1 at 4:08:27 AM
npm http request GET https://registry.npmjs.org/aws-sdk-promise
npm info attempt registry request try #1 at 4:08:27 AM
npm http request GET https://registry.npmjs.org/bluebird
npm http 200 https://registry.npmjs.org/aws-sdk
npm info retry fetch attempt 1 at 4:08:27 AM
npm info attempt registry request try #1 at 4:08:27 AM
npm http fetch GET https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.6.6.tgz
npm http 200 https://registry.npmjs.org/bluebird
npm http fetch 200 https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.6.6.tgz
npm http 200 https://registry.npmjs.org/aws-sdk-promise
npm WARN deprecated aws-sdk-promise@0.0.2: stop using this library.  use a recent aws-sdk library instead.  note that you will need to stop looking at the .data property of return values
npm info retry fetch attempt 1 at 4:08:27 AM
npm info attempt registry request try #1 at 4:08:27 AM
npm http fetch GET https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz
npm info retry fetch attempt 1 at 4:08:27 AM
npm info attempt registry request try #1 at 4:08:27 AM
npm http fetch GET https://registry.npmjs.org/aws-sdk-promise/-/aws-sdk-promise-0.0.2.tgz
npm http fetch 200 https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz
npm http fetch 200 https://registry.npmjs.org/aws-sdk-promise/-/aws-sdk-promise-0.0.2.tgz
npm info install aws-sdk-promise@0.0.2 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service
npm info install bluebird@2.11.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service
npm info install aws-sdk@2.6.6 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service
npm info installOne aws-sdk-promise@0.0.2
npm info installOne bluebird@2.11.0
npm info installOne aws-sdk@2.6.6
npm info preinstall aws-sdk-promise@0.0.2
npm info attempt registry request try #1 at 4:08:28 AM
npm http request GET https://registry.npmjs.org/promise
npm http 200 https://registry.npmjs.org/promise
npm info retry fetch attempt 1 at 4:08:28 AM
npm info attempt registry request try #1 at 4:08:28 AM
npm http fetch GET https://registry.npmjs.org/promise/-/promise-6.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/promise/-/promise-6.1.0.tgz
npm info install promise@6.1.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk-promise
npm info installOne promise@6.1.0
npm info preinstall promise@6.1.0
npm info attempt registry request try #1 at 4:08:29 AM
npm http request GET https://registry.npmjs.org/asap
npm http 200 https://registry.npmjs.org/asap
npm info retry fetch attempt 1 at 4:08:29 AM
npm info attempt registry request try #1 at 4:08:29 AM
npm http fetch GET https://registry.npmjs.org/asap/-/asap-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/asap/-/asap-1.0.0.tgz
npm info install asap@1.0.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk-promise/node_modules/promise
npm info installOne asap@1.0.0
npm info preinstall asap@1.0.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk-promise/node_modules/promise/node_modules/asap
npm info preinstall bluebird@2.11.0
npm info linkStuff asap@1.0.0
npm info install asap@1.0.0
npm info postinstall asap@1.0.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk-promise/node_modules/promise
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/bluebird
npm info linkStuff promise@6.1.0
npm info linkStuff bluebird@2.11.0
npm info install promise@6.1.0
npm info postinstall promise@6.1.0
npm info install bluebird@2.11.0
npm info postinstall bluebird@2.11.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk-promise
npm info linkStuff aws-sdk-promise@0.0.2
npm info install aws-sdk-promise@0.0.2
npm info postinstall aws-sdk-promise@0.0.2
npm info preinstall aws-sdk@2.6.6
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/jmespath
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/querystring
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/sax
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/url
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/xml2js
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/xmlbuilder
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/buffer
npm info attempt registry request try #1 at 4:08:33 AM
npm http request GET https://registry.npmjs.org/crypto-browserify
npm http 200 https://registry.npmjs.org/jmespath
npm http 200 https://registry.npmjs.org/querystring
npm http 200 https://registry.npmjs.org/sax
npm http 200 https://registry.npmjs.org/url
npm http 200 https://registry.npmjs.org/xmlbuilder
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/jmespath/-/jmespath-0.15.0.tgz
npm http 200 https://registry.npmjs.org/crypto-browserify
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz
npm http 200 https://registry.npmjs.org/xml2js
npm http fetch 200 https://registry.npmjs.org/jmespath/-/jmespath-0.15.0.tgz
npm http 200 https://registry.npmjs.org/buffer
npm http fetch 200 https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/sax/-/sax-1.1.5.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/url/-/url-0.10.3.tgz
npm http fetch 200 https://registry.npmjs.org/sax/-/sax-1.1.5.tgz
npm http fetch 200 https://registry.npmjs.org/url/-/url-0.10.3.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-2.6.2.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-1.0.9.tgz
npm http fetch 200 https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-2.6.2.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/xml2js/-/xml2js-0.4.15.tgz
npm info retry fetch attempt 1 at 4:08:33 AM
npm info attempt registry request try #1 at 4:08:33 AM
npm http fetch GET https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz
npm http fetch 200 https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-1.0.9.tgz
npm http fetch 200 https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz
npm http fetch 200 https://registry.npmjs.org/xml2js/-/xml2js-0.4.15.tgz
npm info install querystring@0.2.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install jmespath@0.15.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install sax@1.1.5 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install url@0.10.3 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install xmlbuilder@2.6.2 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install xml2js@0.4.15 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install buffer@4.9.1 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info install crypto-browserify@1.0.9 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info installOne querystring@0.2.0
npm info installOne jmespath@0.15.0
npm info installOne sax@1.1.5
npm info installOne url@0.10.3
npm info installOne xmlbuilder@2.6.2
npm info installOne xml2js@0.4.15
npm info installOne buffer@4.9.1
npm info installOne crypto-browserify@1.0.9
npm info preinstall sax@1.1.5
npm info preinstall xml2js@0.4.15
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/sax
npm info preinstall url@0.10.3
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/xml2js
npm info linkStuff sax@1.1.5
npm info install sax@1.1.5
npm info linkStuff xml2js@0.4.15
npm info postinstall sax@1.1.5
npm info install xml2js@0.4.15
npm info postinstall xml2js@0.4.15
npm info attempt registry request try #1 at 4:08:34 AM
npm http request GET https://registry.npmjs.org/punycode
npm http 200 https://registry.npmjs.org/punycode
npm info retry fetch attempt 1 at 4:08:34 AM
npm info attempt registry request try #1 at 4:08:34 AM
npm http fetch GET https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz
npm info preinstall querystring@0.2.0
npm http fetch 200 https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/querystring
npm info install punycode@1.3.2 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/url
npm info installOne punycode@1.3.2
npm info linkStuff querystring@0.2.0
npm info install querystring@0.2.0
npm info postinstall querystring@0.2.0
npm info preinstall xmlbuilder@2.6.2
npm info attempt registry request try #1 at 4:08:34 AM
npm http request GET https://registry.npmjs.org/lodash
npm info preinstall punycode@1.3.2
npm http 200 https://registry.npmjs.org/lodash
npm info retry fetch attempt 1 at 4:08:34 AM
npm info attempt registry request try #1 at 4:08:34 AM
npm http fetch GET https://registry.npmjs.org/lodash/-/lodash-3.5.0.tgz
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/url/node_modules/punycode
npm http fetch 200 https://registry.npmjs.org/lodash/-/lodash-3.5.0.tgz
npm info linkStuff punycode@1.3.2
npm info install punycode@1.3.2
npm info postinstall punycode@1.3.2
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/url
npm info linkStuff url@0.10.3
npm info install url@0.10.3
npm info postinstall url@0.10.3
npm info install lodash@3.5.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/xmlbuilder
npm info installOne lodash@3.5.0
npm info preinstall jmespath@0.15.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/jmespath
npm info linkStuff jmespath@0.15.0
npm info install jmespath@0.15.0
npm info postinstall jmespath@0.15.0
npm info preinstall buffer@4.9.1
npm info attempt registry request try #1 at 4:08:35 AM
npm http request GET https://registry.npmjs.org/isarray
npm info attempt registry request try #1 at 4:08:35 AM
npm http request GET https://registry.npmjs.org/base64-js
npm info attempt registry request try #1 at 4:08:35 AM
npm http request GET https://registry.npmjs.org/ieee754
npm http 200 https://registry.npmjs.org/isarray
npm http 200 https://registry.npmjs.org/ieee754
npm http 200 https://registry.npmjs.org/base64-js
npm info retry fetch attempt 1 at 4:08:35 AM
npm info attempt registry request try #1 at 4:08:35 AM
npm http fetch GET https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz
npm info retry fetch attempt 1 at 4:08:35 AM
npm info attempt registry request try #1 at 4:08:35 AM
npm http fetch GET https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz
npm info retry fetch attempt 1 at 4:08:35 AM
npm info attempt registry request try #1 at 4:08:35 AM
npm http fetch GET https://registry.npmjs.org/base64-js/-/base64-js-1.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz
npm http fetch 200 https://registry.npmjs.org/base64-js/-/base64-js-1.2.0.tgz
npm info install isarray@1.0.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer
npm info install ieee754@1.1.8 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer
npm info install base64-js@1.2.0 into /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer
npm info installOne isarray@1.0.0
npm info installOne ieee754@1.1.8
npm info installOne base64-js@1.2.0
npm info preinstall ieee754@1.1.8
npm info preinstall isarray@1.0.0
npm info preinstall base64-js@1.2.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer/node_modules/ieee754
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer/node_modules/isarray
npm info linkStuff ieee754@1.1.8
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer/node_modules/base64-js
npm info install ieee754@1.1.8
npm info linkStuff isarray@1.0.0
npm info postinstall ieee754@1.1.8
npm info install isarray@1.0.0
npm info postinstall isarray@1.0.0
npm info linkStuff base64-js@1.2.0
npm info install base64-js@1.2.0
npm info postinstall base64-js@1.2.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/buffer
npm info linkStuff buffer@4.9.1
npm info install buffer@4.9.1
npm info postinstall buffer@4.9.1
npm info preinstall crypto-browserify@1.0.9
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/crypto-browserify
npm info linkStuff crypto-browserify@1.0.9
npm info install crypto-browserify@1.0.9
npm info postinstall crypto-browserify@1.0.9
npm info preinstall lodash@3.5.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/xmlbuilder/node_modules/lodash
npm info linkStuff lodash@3.5.0
npm info install lodash@3.5.0
npm info postinstall lodash@3.5.0
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk/node_modules/xmlbuilder
npm info linkStuff xmlbuilder@2.6.2
npm info install xmlbuilder@2.6.2
npm info postinstall xmlbuilder@2.6.2
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service/node_modules/aws-sdk
npm info linkStuff aws-sdk@2.6.6
npm info install aws-sdk@2.6.6
npm info postinstall aws-sdk@2.6.6
npm info build /usr/src/ghost/content/storage/ghost-s3/node_modules/ghost-s3-service
npm info linkStuff ghost-s3-service@1.0.2
npm info install ghost-s3-service@1.0.2
npm info postinstall ghost-s3-service@1.0.2
ghost-s3-service@1.0.2 node_modules/ghost-s3-service
├── bluebird@2.11.0
├── aws-sdk-promise@0.0.2 (promise@6.1.0)
└── aws-sdk@2.6.6 (sax@1.1.5, xml2js@0.4.15, querystring@0.2.0, url@0.10.3, jmespath@0.15.0, buffer@4.9.1, crypto-browserify@1.0.9, xmlbuilder@2.6.2)
npm info ok
 ---> 611a7944cf16
```

**Comment by kelyvin** [comment] 2016-10-06 04:16
Hi Andy, 

Let me look into this and I will hopefully get back to you in the next couple of days. Also looks like you're trying on ghost v0.11.*, which I haven't tried myself yet. Stay tuned!

**Comment by pascalandy** [comment] 2016-10-06 10:51
Thanks!

**Comment by pascalandy** [comment] 2016-10-07 12:20
You might be interested to follow this conversation as well https://github.com/spanishdict/ghost-s3-compat/pull/11#issuecomment-251944225 (acburdine is from the Ghost Core Team)

Cheers!

**Comment by jlucasps** [comment] 2016-10-10 03:04
I've got a similar issue when tried to run `sudo npm start --production`:

Error:

```
ERROR: Your storage adapter does not inherit from the Storage Base. 

 Error
    at Error.IncorrectUsage (/var/www/ghost/core/server/errors/incorrect-usage.js:3:18)
    at Object.getStorage (/var/www/ghost/core/server/storage/index.js:54:15)
    at setupMiddleware (/var/www/ghost/core/server/middleware/index.js:126:44)
    at config.load.then.then.then.then.then.then.then.then.then.then.then.ghostServer (/var/www/ghost/core/server/index.js:188:9)
    at tryCatcher (/var/www/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/www/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/var/www/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/www/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/var/www/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/var/www/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/var/www/ghost/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/var/www/ghost/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/var/www/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/www/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/var/www/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/www/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/var/www/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickDomainCallback (node.js:459:13) 
```

**Details:**
Ghost version: 0.11.1
Database: MySQL
Node: v0.10.25
npm: 2.5.0
OS: Ubuntu 14.04

**Comment by pascalandy** [comment] 2016-10-11 03:24
@jlucasps you need to upgrade to node 4.x. V0.10 is not supported anymore. Cheers!

I still have the same issue.

**Comment by kelyvin** [comment] 2016-10-11 04:26
Hi folks, 

Been traveling around a bit and finally have a moment to breathe. I promise i'll take a look at it this week! Sorry for the delay and thanks for your patience!

**Comment by jlucasps** [comment] 2016-10-12 19:00
OK, thanks @pascalandy and @kelyvin.

Regards.

**Comment by dting** [comment] 2016-10-14 10:08
@pascalandy @kelyvin I think i've nailed down the problem and made a PR to add the `util` module as a dependency. Seems to fix the issue for me.

**Comment by pascalandy** [comment] 2016-10-15 16:17
Can't wait to try this ! Will wait for your merge @kelyvin 

Cheers!

**Comment by kelyvin** [comment] 2016-10-17 07:52
Thanks @dting for the pull request and thanks @pascalandy & @jlucasps for your patinence! I haven't had the proper time to test this (been busy moving apartments). However, I don't want to be your bottlenecks and prevent you both from moving forward. So in the meantime, I have merged the pull request into the following [util-update branch](https://github.com/kelyvin/ghost-s3-service/tree/util-update). 

Given the nature of the fix, I feel there may be a better way to resolve the package management. For now this will have to do and I hope to get to this more thoroughly soon once I have settled in. I promise I'm usually not this unresponsive, the past couple months have been a combination of studying + changing jobs + traveling + moving. Almost settled in and I appreciate your patience!

Thanks!

**Comment by pascalandy** [comment] 2016-10-17 13:21
It's all good @kelyvin :) 

I understand the npm project stays unmodified. Therefore this branch won't fix the issue at the moment.

```
'use strict';
module.exports = require('ghost-s3-service');
```

I'll stay tune :)

**Comment by rmartin** [comment] 2016-10-18 07:06
hey @pascalandy , 

Thanks for opening the issue and thanks to @kelyvin and @dting for working on the resolution. I ran into this when upgrading my blog this weekend. One thing to note @pascalandy is that you don't need to wait for the update to be officially released to NPM to be able to leverage this. You just need to point the node package directly to the github repository branch that @kelyvin outlined above. Note I also needed to include the aws-sdk following depdency in my project

`npm install --production https://github.com/kelyvin/ghost-s3-service/tarball/util-update --save`
`npm install --production aws-sdk --save`

If you're using Heroku to host the application then you'll also have to [disable the node_module cache to incorporate this](https://devcenter.heroku.com/articles/nodejs-support#cache-behavior).

Hopefully that helps in the meantime.  I can confirm that I was able to get this to work was expected with an upgrade from 0.7.x to 0.11.2. I would encourage the merge of this patch into master and publish it in NPM in the meantime as the current code is current broken against the current release. Then perhaps raise a new PR for improving the method of requiring those dependencies. 

Thanks again for your support in making this work!

Cheers,
Roy

**Comment by dting** [comment] 2016-10-18 08:35
I think another possibility is not to use `util.inherits` and just set the `prototype` and `constructor`:

```
function S3Store(config) {
    BaseStore.call(this);
    options = config;
}

S3Store.prototype = Object.create(BaseStore.prototype);
S3Store.constructor = S3Store;
```

Thoughts?

**Comment by pascalandy** [comment] 2016-10-19 15:05
@rmartin You rock!
I don't know anything about deploying/packaging stuff via NPM so this is highly appreciated :) Will try ASAP :)

**Comment by pascalandy** [comment] 2016-10-19 15:16
@rmartin You rock!
I don't know anything about deploying/packaging stuff via NPM so this is highly appreciated :) Will try ASAP :) cc @jwasham

**Comment by pascalandy** [comment] 2016-10-20 16:00
@kelyvin 
I thought you should be aware of this. @acburdine from the Ghost team pushed a update as well.
https://github.com/spanishdict/ghost-s3-compat/pull/11#issuecomment-255111493

Cheers!

**Comment by kelyvin** [comment] 2016-11-14 00:19
Finally have time again! Woot! Sorry that took so long. 

Trying to play some catch up, anyone still running into any issues with this? Any status updates or anything I should know before taking a look at this?

**Comment by marybeshaw** [comment] 2016-11-19 02:26
Hi, I am trying to install ghost on heroku using ghost-s3-storage and am running into this same issue.  I am pinned to npm ^0.2.2 ; what version do I pin to, in order to get a fix?

**Comment by pascalandy** [comment] 2016-12-14 23:43
I install successfully Ghost 0.11.2 with this storage plugin :)

I followed @rmartin instructions:

```
npm install --production https://github.com/kelyvin/ghost-s3-service/tarball/util-update --save
npm install --production aws-sdk --save
```

Here is how the tree looks like on my machine:

```
root@43b5979dd325:/usr/src/ghost/content# ls
apps  data  images  storage  themes

root@43b5979dd325:/usr/src/ghost/content/storage# ls
ghost-s3-service

root@43b5979dd325:/usr/src/ghost/content/storage/ghost-s3-service# ls
index.js

root@43b5979dd325:/usr/src/ghost# ls
Gruntfile.js  LICENSE  PRIVACY.md  README.md  config.example.js  config.js  content  core  index.js  node_modules  npm-shrinkwrap.json	package.json

root@43b5979dd325:/usr/src/ghost/node_modules# ls
accepts        bookshelf	csv-parser	extend			  html-to-text	      jsonpath	       moment		normalize-path			 passport-strategy     sqlite3	    xtend
amperize       chalk		depd		extract-zip-fork	  htmlparser2	      knex	       moment-timezone	oauth2orize			 path-match	       superagent
archiver       cheerio		dom-serializer	fs-extra		  iconv-lite	      lodash	       morgan		on-finished			 pg		       type-is
aws-sdk        commander	domelementtype	generate-object-property  image-size	      lodash.defaults  multer		on-headers			 pg-connection-string  unidecode
babel-runtime  compression	domutils	ghost-gql		  inherits	      lodash.merge     mysql		once				 qs		       unpipe
bcryptjs       connect-slashes	downsize	ghost-s3-service	  ini		      methods	       netjet		optimist			 rss		       utils-merge
bl	       content-type	entities	glob			  intl		      mime-types       node-uuid	passport			 sanitize-html	       validator
bluebird       cookie-session	express		graceful-fs		  intl-messageformat  minimatch        nodemailer	passport-http-bearer		 semver		       vary
body-parser    cors		express-hbs	gscan			  isobject	      mkdirp	       nopt		passport-oauth2-client-password  showdown-ghost        xml

root@43b5979dd325:/usr/src/ghost/node_modules/ghost-s3-service# ls
CHANGELOG.md  LICENSE  README.md  index.js  node_modules  package.json

root@43b5979dd325:/usr/src/ghost/node_modules/ghost-s3-service/node_modules# ls
aws-sdk  aws-sdk-promise  bluebird  util
root@43b5979dd325:/usr/src/ghost/node_modules/ghost-s3-service/node_modules#
```

@kelyvin I think you should **merge branch `util-update`** and a big thanks to @dting for the fix :)

**Comment by kelyvin** [comment] 2016-12-15 07:56
Thanks for the response @pascalandy, if it's working for you then I will go ahead and pull the change, which you can find here: https://github.com/kelyvin/ghost-s3-service/commit/a4949dd16fe9d57f73a6b82b23bdea472fe3e458

Thanks for verifying and for your patience!

**Closed as completed by kelyvin** 2016-12-15 07:56 UTC
Labels: question
